Test enhancement
kylekatarnls/simple-cli pull request #4
Opened 2020-01-20 10:42 UTC by peter279k

# Changed log
- According to the [official PHPUnit doc](https://phpunit.de/manual/7.0/en/appendixes.assertions.html#appendixes.assertions.static-vs-non-static-usage-of-assertion-methods), it can use the `$this` or `self` to make assertion method calls.
Using the `self` to replace the `static`.
- To be compatible with the PHPUnit fixture methods, adding the native `void` type hint.
- Changing into the `"Tests\\SimpleCli\\": "tests/SimpleCli/"` to make `autoload-dev` clear to know loading test classes.

2020-01-20 11:05 UTC, kylekatarnls commented
`static::assertSame` is fine, especially for `static::assertOutput` which is a custom assertion, here is the difference:

```php
class Foo
{
  public function assert()
  {
    return 'assert Foo';
  }

  public function test()
  {
    echo $this->assert() . "\n";
    echo self::assert() . "\n";
    echo static::assert() . "\n";
  }
}

class Bar extends Foo
{
  public function assert()
  {
    return parent::assert() . ' and Bar';
  }
}

$bar = new Bar;
$bar->test();
```

Output (https://3v4l.org/v6h1p):
```
assert Foo and Bar
assert Foo
assert Foo and Bar
```

So as you can see `static::` matches `$this->` while `self::` ignores methods overrides.
And while `$this->` let you think the result can depends on the context (`$this`), `static::` and `self::` make it clear it does not.

Extending a class containing tests is not so common but it can be pretty cool to run twice the same tests with just small changes such as run tests with both `DateTime` and `DateTimeImmutable` to check it behave the same.

2020-01-21 03:13 UTC, peter279k commented
@kylekatarnls, agree. Revert these assertion method calls.

2020-01-21 07:04 UTC, kylekatarnls commented on src/SimpleCli/SimpleCliCommand/Create.php
> +    use Verbose;
Please let a blank line after imports.

2020-01-21 07:04 UTC, kylekatarnls commented on tests/SimpleCli/DemoApp/DemoCommand.php
> +    use Help;
Please let a blank line after imports.

2020-01-21 07:04 UTC, kylekatarnls commented on tests/SimpleCli/DemoApp/TraitCommand.php
> +    use Input;
Please let a blank line after imports.

2020-01-21 07:06 UTC, kylekatarnls requested changes
Thanks, changes are good. I have to check the initial reason of `@var Help $helper` I think there was an issue with PHPStorm to properly detect the type for auto-completion.

2020-01-28 11:30 UTC, kylekatarnls commented
It's feel legit but I'm a bit annoyed by the PHPStorm autocompletion:
Before:
![image](https://user-images.githubusercontent.com/5966783/73260268-dec66f80-41c9-11ea-9f79-8900c4d0e072.png)

After:
![image](https://user-images.githubusercontent.com/5966783/73259956-2bf61180-41c9-11ea-9aeb-32a7b56641fd.png)

2020-01-28 13:40 UTC, kylekatarnls commented
Partially merged via https://github.com/kylekatarnls/simple-cli/commit/83fca9ef59d8ae15a25812d8be61de9b5ddca948

And I added my StyleCI config as a inner file so any fork will have the `phpdoc_var_without_name` exception by default.

2020-01-28 13:40 UTC, closed without merging